name: Compatibility tests 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compatibility_tests_macos:
    name: Execute compatibility tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-26
            xcode-version: "26.6"   # Swift 6.3.3
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Xcode
        uses: OpenSwiftUIProject/setup-xcode@v2
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Swift version
        run: swift --version
      - name: Run tests against Apple's Combine
        run: make test-compatibility
      - name: Build with library evolution
        run: make library-evolution
      - name: Generate swiftinterface
        run: make module-interface
      - name: Build without private header of OSLock
        run: make disable-oslock-private
