name: SwiftLint

on:
  pull_request:
    paths:
      - ".github/workflows/swiftlint.yml"
      - ".swiftlint.yml"
      - "Tests/.swiftlint.yml"
      - "utils/lint.sh"
      - "**/*.swift"

jobs:
  SwiftLint:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Xcode
        uses: OpenSwiftUIProject/setup-xcode@v2
        with:
          xcode-version: "26.6"
      - name: Check new SwiftLint violations
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: bash utils/lint.sh "$BASE_SHA"
