name: Wasm 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  wasm_test:
    name: Execute tests on WASM
    runs-on: ubuntu-24.04
    container: swift:6.3.3-noble
    steps:
      - uses: actions/checkout@v6
      - name: Install Swift SDK for WebAssembly
        run: |
          swift sdk install \
            https://download.swift.org/swift-6.3.3-release/wasm-sdk/swift-6.3.3-RELEASE/swift-6.3.3-RELEASE_wasm.artifactbundle.tar.gz \
            --checksum cabfa08b73bb8ac783927ecd15fa386e99d0c139c5f232445067bcf58379cae7
      - name: Build and run tests on WebAssembly
        run: swift test --swift-sdk swift-6.3.3-RELEASE_wasm
