name: Windows 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  windows_test:
    name: Execute tests on Windows
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025
            swift_version: "6.3.3"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-${{ matrix.swift_version }}-release
          swift-build: ${{ matrix.swift_version }}-RELEASE
      - name: Building and running tests in debug mode
        run: swift test
